# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore",
      readonly: true,
      app_identifier: "net.artkernel.CodeMagicDemo2",
      profile_name: "*** AppStore net.artkernel.CodeMagicDemo2",
      keychain_name: ENV['AK_KEYCHAIN_NAME'],
      keychain_password: ENV['AK_KEYCHAIN_PASS'],
      git_url: ENV['AK_MATCH_GIT_REPO'],
      git_private_key: ENV['AK_MATCH_GIT_REPO_KEY'])

    
    increment_build_number(xcodeproj: "CodeMagicDemo.xcodeproj")
    build_app(workspace: "CodeMagicDemo.xcworkspace", scheme: "CodeMagicDemo")
    upload_to_testflight
  end
end
